admin_panel/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from companies_app.api_views import CompanyViewSet, DepartmentViewSet
from users_app.api_views import UserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'departments', DepartmentViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys_app.urls', namespace='surveys')),
    path('companies/', include('companies_app.urls', namespace='companies')),
    path('users/', include('users_app.urls', namespace='users')),
    path('quiz/', include('quiz_app.urls', namespace='quiz')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

admin_panel/quiz_app/urls.py
from django.urls import path
from quiz_app import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'quiz_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
    path('<int:poll_id>/vote/', csrf_exempt(views.vote), name='vote'),
    path('<int:pk>)/results/', csrf_exempt(views.ResultsView.as_view()), name='results'),


]

admin_panel/users_app/urls.py
from django.urls import path
from users_app import views
from django.contrib.auth.views import LogoutView


app_name = 'users_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('search/', views.UserSearchView.as_view(), name='search_results'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('profile/<int:pk>/', views.UserUpdateView.as_view(), name='profile'),
    path('confirm_delete/<int:pk>/', views.UserDelete.as_view(), name='confirm_delete'),
    path('passchange/<int:pk>/', views.UserPasswordChangeView.as_view(), name='passchange'),
    path('passreset/<int:pk>/', views.UserPasswordResetView.as_view(), name='passreset'),

    ]

admin_panel/users_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group
from django.db import models
from django.utils.translation import ugettext_lazy as _
from companies_app.models import Company


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""
    username = None
    email = models.EmailField(_('email address'), unique=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_avatars')
    companies = models.ManyToManyField(Company, blank=True, verbose_name='Компании')
    groups = models.ManyToManyField(Group, blank=True, verbose_name='Группы')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        # ordering = ["last_name"]
        ordering = ["email"]

admin_panel/users_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'placeholder': 'bruce@wayne.com',
                                                           'class': "form-control rounded-0"}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.TextInput(attrs={'placeholder': 'At least 8 characters',
                                                              'class': "form-control rounded-0"}))
    password2 = forms.CharField(label='Подтвердить пароль',
                                widget=forms.TextInput(attrs={'class': "form-control rounded-0"}))

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

admin_panel/users_app/views.py
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from .forms import RegistrationForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import User


# Create your views here.
# def get_absolute_url(self):
#     return reverse('user_detail', kwargs={'pk': self.pk})


class UserLoginView(LoginView):
    template_name = 'users_app/login.html'


class RegisterUserCreateView(CreateView):
    model = User
    template_name = 'users_app/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')


# ListView
class UsersListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'users_app/users.html'

    def get_context_data(self, *args, **kwargs):
        """
        :param object_list:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['user_name'] = 'Пользователи'
        return context


class UserSearchView(ListView):
    model = User
    template_name = 'users_app/search_results.html'

    def get_queryset(self):  # new
        query = self.request.GET.get('q')
        object_list = User.objects.filter(Q(email__icontains=query) |
                                          Q(first_name__icontains=query) |
                                          Q(last_name__icontains=query))

        return object_list


# CreateView
class UserCreateView(LoginRequiredMixin, CreateView):
    fields = ('email', 'first_name')

    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users_app/create.html'

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)


# DetailView
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users_app/user.html'


# UpdateView
class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ('email', 'first_name', 'last_name', 'avatar')

    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users_app/profile.html'


# DeleteView
class UserDelete(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users_app/confirm_delete.html'


# ChangePass
class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users_app/passchange.html'


# PasswordResetView
class UserPasswordResetView(LoginRequiredMixin, PasswordResetView):
    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users_app/passreset.html'

admin_panel/users_app/templates/users_app/passchange.html
{% extends "base.html" %}
 {% load static %}
{% block title %} login {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=object.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
<div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">

        <div class="col-lg-6">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome!</h1>
                </div>
                <div class="row justify-content-md-center">
                    <form class="col-lg-6" method="post">

                    {% csrf_token %}
                    {{ form.as_ul }}
                    <button type="submit" class="btn btn-primary btn-user btn-block">Отправить</button>
                </form>

                </div>
            </div>
        </div>
        <div class="col-lg-6 d-none d-lg-block">
                <div class="text-center">
                   <img src="{% static 'bootstrap/img/laptop.png' %}" width=80%>
                </div>
        </div>
    </div>
    <hr>
            <div class="text-center">
                <a class="small" href="forgot-password.html">Забыли пароль?</a>
            </div>
            <div class="text-center">
                <a class="small" href="{% url 'users:register' %}">Зарегистрироваться!</a>
            </div>
    <hr>
    {% endblock %}

admin_panel/users_app/templates/users_app/passreset.html
{% extends "base.html" %}
 {% load static %}
{% block title %} login {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
<div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">

        <div class="col-lg-6">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome!</h1>
                </div>
                <div class="row justify-content-md-center">
                    <form class="col-lg-6" method="post">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-user btn-block">Отправить</button>
                </form>

                </div>
            </div>
        </div>
        <div class="col-lg-6 d-none d-lg-block">
                <div class="text-center">
                   <img src="{% static 'bootstrap/img/laptop.png' %}" width=80%>
                </div>
        </div>
    </div>
    <hr>
            <div class="text-center">
                <a class="small" href="forgot-password.html">Забыли пароль?</a>
            </div>
            <div class="text-center">
                <a class="small" href="{% url 'users:register' %}">Зарегистрироваться!</a>
            </div>
    <hr>
    {% endblock %}

admin_panel/users_app/templates/users_app/search_results.html
{% extends "base.html" %}
{% block title %} Карточка сотрудника {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>



            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">
     {% for item in object_list %}
    <a href="{% url 'users:user' pk=item.pk %}" style="text-decoration: none;">
     <div class="row col-md-12">
        <div class="col-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters ">
                        <div class="col-md-1 d-flex ">
                            {% if item.avatar %}
                            <img src="{{item.avatar.url}}" width="40">
                            {% else %}
                            <i class="fas fa-user fa-2x text-gray-300"> </i>
                            {% endif %}
                        </div>
                        <div class="col-md-5 font-weight-bold text-primary text-uppercase mb-1">{{ item.email }}</div>
                        <div class="col-md-1 d-flex" style="color:black;" >{{ item.first_name }}</div>
                        <div class="col-md-1 d-flex" style="color:black;" >{{ item.last_name }}</div>
                    </div>

                </div>
            </div>
        </div>
    </div><br>
         </a>
    {% endfor  %}
</div>
<!-- /.container-fluid -->

{% endblock %}

admin_panel/users_app/templates/users_app/user.html
{% extends "base.html" %}
{% block title %} {{object.email}} {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{% url 'users:passchange' pk=object.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Сменить пароль
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Редактировать Компании
                    </a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="col">
        {% if user.avatar %}
        <img src="{{user.avatar.url}}" width="40">
        {% else %}
        <i class="fas fa-user fa-2x text-gray-300"> </i>
        {% endif %}
    </div>
    <div class="col">
        {{ user.email }}{{ user.first_name }}{{ user.last_name }}
        <a href="{% url 'users:profile' pk=object.id %}"
           class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-sm text-white-50"></i>
            Profile</a>
        <a href="{% url 'users:confirm_delete' pk=object.id %}"
           class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-sm text-white-50"></i>
            Delete</a>
    </div>
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h3 class="h3 mb-0 text-gray-800">Компании:</h3>
    </div>


     {% for item in user.companies.all %}
     <div class="row col-md-12">
        <div class="col-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters ">
                        <div class="col-md-3 font-weight-bold text-primary text-uppercase mb-1">{{ item.name }}</div>
                    </div>

                </div>
            </div>
        </div>
    </div><br>
    {% endfor  %}





</div>
{% endblock %}

admin_panel/users_app/templates/users_app/users.html
{% extends "base.html" %}
{% block title %} Пользователи {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form method="GET"
                  action="{% url 'users:search_results' %}"
                  class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text"
                           class="form-control bg-light border-0 small"
                           placeholder="Поиск ..."
                           aria-label="Search"
                           aria-describedby="basic-addon2"
                           name="q">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <i class="fa fa-user "> Управление</i>
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0" style="color:black;">{{user_name}}</h1>
        <a href="{% url 'users:create' %}"
           class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-sm text-white-50"></i>
            ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ</a>
    </div>
    <!-- Content Row -->


     {% for item in object_list %}
    <a href="{% url 'users:user' pk=item.pk %}" style="text-decoration: none;">
     <div class="row col-md-12">
        <div class="col-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters ">
                        <div class="col-md-1 d-flex ">
                            {% if item.avatar %}
                            <img src="{{item.avatar.url}}" width="40">
                            {% else %}
                            <i class="fas fa-user fa-2x text-gray-300"> </i>
                            {% endif %}
                        </div>
                        <div class="col-md-5 font-weight-bold text-primary text-uppercase mb-1">{{ item.email }}</div>
                        <div class="col-md-1 d-flex" style="color:black;" >{{ item.first_name }}</div>
                        <div class="col-md-1 d-flex" style="color:black;" >{{ item.last_name }}</div>
                    </div>

                </div>
            </div>
        </div>
    </div><br>
         </a>
    {% endfor  %}

</div>
<!-- /.container-fluid -->
{% endblock %}