admin_panel/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from companies_app.api_views import CompanyViewSet, DepartmentViewSet
from users_app.api_views import UserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'departments', DepartmentViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys_app.urls', namespace='surveys')),
    path('companies/', include('companies_app.urls', namespace='companies')),
    path('users/', include('users_app.urls', namespace='users')),
    path('quiz/', include('quiz_app.urls', namespace='quiz')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

admin_panel/companies_app/urls.py
from django.urls import path
from companies_app import views

app_name = 'companies_app'

urlpatterns = [


    path('companies/', views.CompaniesListView.as_view(), name='companies'),
    path('search/', views.CompanySearchView.as_view(), name='search_results'),
    path('users/<int:pk>/', views.CompanyDetailView.as_view(), name='users'),
    path('company_structure/<int:pk>/', views.CompanyDepartmentsDetailView.as_view(), name='company_structure'),
    path('surveys/<int:pk>/', views.CompanySurveysDetailView.as_view(), name='surveys'),
    path('company_add_department/<int:pk>/', views.AddDepartmentDetailView.as_view(), name='company_add_department'),
    path('add_department/<int:pk>/', views.AddDepartmentCreateView.as_view(), name='add_department'),
    path('create/', views.CompanyCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CompanyUpdateView.as_view(), name='update'),
    path('confirm_delete/<int:pk>/', views.CompanyDelete.as_view(), name='confirm_delete'),
    # path('add_department/', views.DepartmentCreateView.as_view(), name='add_department'),
    # path('structure/<int:pk>/', views.StructureDetailView.as_view(), name='structure'),
    # path('structure/<int:id>/', views.show_structure, name='structure'),
    # path('structure/', views.show_structure, name='structure'),
    # path('departments/', views.DepartmentsListView.as_view(), name='departments'),


]

admin_panel/quiz_app/urls.py
from django.urls import path
from quiz_app import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'quiz_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
    path('<int:poll_id>/vote/', csrf_exempt(views.vote), name='vote'),
    path('<int:pk>)/results/', csrf_exempt(views.ResultsView.as_view()), name='results'),


]

admin_panel/surveys_app/urls.py
from django.urls import path
from surveys_app import views
from surveys_app.forms import StepOneForm, StepTwoForm, StepThreeForm

app_name = 'surveys_app'

# named_contact_forms = (
#     ('contactdata', StepOneForm),
#     ('leavemessage', StepTwoForm),
# )

urlpatterns = [
    path('', views.main_view, name='index'),

    path('add_survey/', views.FormWizardView.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='add_survey'),
    path('surveys/', views.SurveysListView.as_view(), name='surveys'),
    path('survey/<int:pk>/', views.SurveyDetailView.as_view(), name='survey'),
    path('del_survey/<int:pk>/', views.SurveyDeleteView.as_view(), name='del_survey'),

    path('hello/<int:pk>/', views.HelloUpdateView.as_view(), name='hello'),
    path('info/<int:pk>/', views.InfoUpdateView.as_view(), name='info'),
    path('bye/<int:pk>/', views.ByeUpdateView.as_view(), name='bye'),
    path('upd_page/<int:pk>/', views.PageUpdateView.as_view(), name='upd_page'),
    path('page/<int:pk>/', views.PageDetailView.as_view(), name='page'),
    path('add/<int:pk>/', views.AddPageCreateView.as_view(), name='add'),
    path('del_page/<int:pk>/', views.PageDeleteView.as_view(), name='del_page'),

    path('add_question/<int:pk>/', views.PageQuestionDetailView.as_view(), name='add_question'),
    path('add_question2/<int:pk>/', views.QuestionCreateView.as_view(), name='add_question2'),
    path('upd_question/<int:pk>/', views.QuestionUpdateView.as_view(), name='upd_question'),
    path('del_question/<int:pk>/', views.QuestionDeleteView.as_view(), name='del_question'),

    path('add_answer/<int:pk>/', views.QuestionAnswerDetailView.as_view(), name='add_answer'),
    path('add_answer2/<int:pk>/', views.QuestionAnswerCreateView.as_view(), name='add_answer2'),

    path('welcome/<int:pk>/', views.SurveyWelcome.as_view(), name='welcome'),
    # path('welcome/<slug:slug>/', views.SurveyWelcome.as_view(), name='welcome'),
    path('instruction/<int:pk>/', views.SurveyInstruction.as_view(), name='instruction'),
    path('see_you_later/<int:pk>/', views.SurveySeeYouLater.as_view(), name='see_you_later'),
    path('pages/<survey_id>', views.SurveyPagesListViewDemo.as_view(), name='pages'),
    path('create/', views.create_respond, name='create'),
    path('pages_d/<int:pk>/', views.PageResponseDetailView.as_view(), name='pages_d'),
    path('pages_d2/<int:pk>/', views.ResponseCreateView.as_view(), name='pages_d2'),
    path('pages_d4/<int:pk>/', views.ResponseCreateView2.as_view(), name='pages_d4'),
    path('pages_d3/<int:pk>/', views.StartSurveyCreateView.as_view(), name='pages_d3'),
    path('questions/<survey_id>', views.SurveyQuestionsListView.as_view(), name='questions'),



]

admin_panel/users_app/urls.py
from django.urls import path
from users_app import views
from django.contrib.auth.views import LogoutView


app_name = 'users_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('search/', views.UserSearchView.as_view(), name='search_results'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('profile/<int:pk>/', views.UserUpdateView.as_view(), name='profile'),
    path('confirm_delete/<int:pk>/', views.UserDelete.as_view(), name='confirm_delete'),
    path('passchange/<int:pk>/', views.UserPasswordChangeView.as_view(), name='passchange'),
    path('passreset/<int:pk>/', views.UserPasswordResetView.as_view(), name='passreset'),

    ]

admin_panel/surveys_app/models.py
import uuid

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from companies_app.models import Company
from django.utils.timezone import now
from fontawesome_5.fields import IconField


def random_string():
    return str(uuid.uuid4().hex[:5].upper())


# Create your models here.
class Language(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        return self.name


class Survey(models.Model):
    name = models.CharField(max_length=64)
    is_draft = models.BooleanField(default=True)
    is_active = models.BooleanField(default=False)
    slug = models.SlugField(null=True, blank=True)
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.CASCADE)
    hello_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Приветствие')
    hello_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    info_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Инструкция')
    info_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    bye_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Завершение')
    bye_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    created_day = models.DateField(default=now)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    contacts = models.TextField(max_length=128, null=True, blank=True)
    answers_counter = models.PositiveIntegerField(null=True, blank=True)
    language = models.ManyToManyField(Language, blank=True,  default='1')

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'опросы'

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('surveys:welcome', kwargs={'slug': self.slug})


class Page(models.Model):
    number = models.SmallIntegerField(null=True, blank=True)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    page_name = models.CharField(max_length=32,  blank=True)
    page_help = models.CharField(max_length=128, blank=True)

    def page_number(self):
        pages = Page.objects.filter(survey=self.survey)
        i = 1
        for page in pages:
            page.number = i
            page.save()
            i += 1
        return self.number

    def get_questions(self):
        questions = self.question_set.all()
        return questions

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'Страницы'


class Question(MPTTModel):
    TYPE_QUESTION = (
        ("Mono", "Mono"),
        ("Poly", "Poly"),
        ("Text", "Text"),
    )
    question_type = models.CharField(max_length=255, choices=TYPE_QUESTION, default='Mono')
    question_title = models.CharField(max_length=128, null=True, blank=True)
    question_help = models.CharField(max_length=128, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='question_image')
    page = models.ForeignKey(Page, on_delete=models.CASCADE, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'вопросы'


class Answer(models.Model):
    icon = IconField(blank=True, null=True)
    question = models.ManyToManyField(Question, blank=True)
    name = models.CharField(max_length=64)
    active_answer = models.BooleanField(default=False)
    radio_buttons = models.BooleanField(default=False)
    drop_down_list = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Предлагаемый вариант ответа'
        verbose_name_plural = 'Предлагаемые варианты ответов'

    def __str__(self):
        return self.name


class UserCode(models.Model):
    code = models.CharField(max_length=5, unique=True, default=random_string)


class Response(models.Model):
    code = models.ForeignKey(UserCode, on_delete=models.CASCADE, null=True, blank=True,)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, blank=True,)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True,)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True,)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Полученный ответ'
        verbose_name_plural = 'Полученные ответы'

admin_panel/surveys_app/forms.py
from django import forms
from django.views.decorators.csrf import csrf_exempt

from .models import Survey, Page, Question, Answer, Response


class ContactForm(forms.Form):
    email = forms.EmailField(label='email',
                             widget=forms.TextInput(attrs={'class': "form-control rounded-0"}))
    message = forms.CharField(label='Сообщение',
                              widget=forms.Textarea(attrs={'placeholder': 'Напишите здесь...',
                                                           'class': "form-control rounded-0"}))


class StepOneForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите название опроса',
                                                         'class': 'form-control'}))


class StepTwoForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()
    # start_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))
    # end_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))


class StepThreeForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ['company', ]


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = []


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ('page', 'parent', 'image',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['name', ]


class ResponseFormDemo(forms.ModelForm):
    # def __init__(self, q_id, *args, **kwargs):
    #     super(ResponseForm, self).__init__(*args, **kwargs)
    #     # self.fields['answer'].queryset = Answer.objects.filter(question=q_id)
    #     # print(self.fields['answer'].queryset)
    #     print(q_id)

    answer = forms.ModelMultipleChoiceField(queryset=Answer.objects.all(),
                                            widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Response
        fields = ['answer', ]


class ResponseForm(forms.ModelForm):

    class Meta:
        model = Response
        fields = ['answer', ]


class SurveyCode(forms.ModelForm):

    class Meta:
        model = Response
        fields = [ ]

admin_panel/surveys_app/templates/surveys_app/add_question.html
{% extends "base.html" %}
{% load mptt_tags %}
{% block title %}  {% endblock %}

{% block content %}
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->


            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                        {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                        {% endif %}
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Выход
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- Page Heading -->

            <!--          <i class="fa fa-sitemap"> Компания</i>-->
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800"> ОПРОС {{ object.survey.name }} ({{ object.survey.id }}) </h1>
                <!--            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-sm text-white-50"></i>СОЗДАТЬ КОМПАНИЮ</a>-->
            </div>


            <div class="row col-md-12">
                <div class="col-12">
                    <div class="card  shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters ">
                                <div class="col-md-9 font-weight-bold text-primary text-uppercase mb-1">
                                    СТРАНИЦА #{{ object.page_number }} {{ object.page_name }} ({{ object.pk}})
                                </div>
                                <div class="col-md-1 font-weight-bold text-primary text-uppercase mb-1">
                                    <form method="post" action="{% url 'surveys:del_page' pk=object.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">
                                            <i class="fa fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </div>
                                <div class="col-md-1 ">
                                    <a href="{% url 'surveys:upd_page' pk=object.id %}">
                                        <i class="fa  fa-edit text-gray-400 fa-2x"></i>
                                    </a>
                                </div>
                            </div>

                            <br>
                            <hr>

                            <div class="card  shadow h-80 py-2">
                                <div class="card-body">



                                     <div class="row no-gutters ">

                                                {% for item in object.question_set.all %}
                                                <div class="col-md-9 font-weight-bold text-primary text-uppercase mb-1">
                                                    <a href="{% url 'surveys:add_answer' pk=item.id  %}">
                                                        вопрос - {{ item.question_title }}
                                                        ({{ item.question_type }} вопрос {{ item.id }})
                                                    </a>
                                                    <hr>
                                                </div>

                                                <div class="col-md-1 font-weight-bold text-primary text-uppercase mb-1">
                                                    <form method="post"
                                                          action="{% url 'surveys:del_question' pk=item.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit"
                                                                class="btn btn-danger"
                                                                style="
                                                    display: flex;
                                                    width:30px;
                                                    height:30px;
                                                    align-items:center;
                                                    justify-content:center;">
                                                            <i class="fa fa-trash-alt"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                         {% endfor %}
                                     </div>

                                    <div class="row col-md-12">
                                        <div class="col-12">
                                            <div class="card  shadow h-100 py-2">
                                                <div class="card-body">
                                                    <form method="post" action="{% url 'surveys:add_question2' pk=object.pk %}">
                                                        {% csrf_token %}
                                                        {{ form.as_p }}
                                                        <button type="submit">Сохранить</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <br>


                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>

        <!-- Content Row -->
    </div>
    <!-- /.container-fluid -->

    {% endblock %}
</div>

admin_panel/surveys_app/templates/surveys_app/surveys.html
{% extends "base.html" %}
{% block title %} Пользователи {% endblock %}

{% block content %}
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form method="GET"
                  action="{% url 'users:search_results' %}"
                  class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text"
                           class="form-control bg-light border-0 small"
                           placeholder="Поиск ..."
                           aria-label="Search"
                           aria-describedby="basic-addon2"
                           name="q">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                        {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                        {% endif %}
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Выход
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">
            <!-- Page Heading -->
            <i class="fa fa-file-alt"> Управление</i>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0" style="color:black;">{{user_name}}</h1>

                <a href="{% url 'surveys:add_survey' %}"
                   class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm "
                   style="border-radius:12px;">
                    <i class="fas fa-sm text-white-50"></i>
                    ДОБАВИТЬ ОПРОС</a>
            </div>
            <!-- Content Row -->


            {% for item in object_list %}

                <div class="row col-md-12">

                    <div class="col-12">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters">

                                    <div class="col-6 font-weight-bold text-primary text-uppercase ">
                                        <a href="{% url 'surveys:survey' pk=item.pk %}" style="text-decoration: none;">
                                        {{ item.name }}
                                        </a>
                                    </div>
                                    <div class="col-1 d-flex" style="color:black;">{{ item.start_date }}</div>
                                    <div class="col-1 d-flex" style="color:black;">{{ item.end_date }}</div>
                                    <div class="col-1 font-weight-bold text-primary text-uppercase mb-1">
<!--                                        <a href="{{ item.get_absolute_url }}">-->

                                            <a href="{% url 'surveys:welcome' pk=item.pk %}">
                                         <button type="submit" class="btn btn-success">
                                                <i class="fa fa-play"> </i>
                                            </button>
                                            </a>
                                    </div>

                                    <div class="col-1 font-weight-bold text-primary text-uppercase mb-1">
                                        <form method="post" action="{% url 'surveys:del_survey' pk=item.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger">
                                                <i class="fa fa-trash-alt"> </i>
                                            </button>
                                        </form>
                                    </div>


                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <br>

            {% endfor %}

        </div>
        <!-- /.container-fluid -->
        {% endblock %}