admin_panel/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from companies_app.api_views import CompanyViewSet, DepartmentViewSet
from users_app.api_views import UserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'departments', DepartmentViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys_app.urls', namespace='surveys')),
    path('companies/', include('companies_app.urls', namespace='companies')),
    path('users/', include('users_app.urls', namespace='users')),
    path('quiz/', include('quiz_app.urls', namespace='quiz')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

admin_panel/companies_app/urls.py
from django.urls import path
from companies_app import views

app_name = 'companies_app'

urlpatterns = [


    path('companies/', views.CompaniesListView.as_view(), name='companies'),
    path('search/', views.CompanySearchView.as_view(), name='search_results'),
    path('users/<int:pk>/', views.CompanyDetailView.as_view(), name='users'),
    path('company_structure/<int:pk>/', views.CompanyDepartmentsDetailView.as_view(), name='company_structure'),
    path('surveys/<int:pk>/', views.CompanySurveysDetailView.as_view(), name='surveys'),
    path('company_add_department/<int:pk>/', views.AddDepartmentDetailView.as_view(), name='company_add_department'),
    path('add_department/<int:pk>/', views.AddDepartmentCreateView.as_view(), name='add_department'),
    path('create/', views.CompanyCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CompanyUpdateView.as_view(), name='update'),
    path('confirm_delete/<int:pk>/', views.CompanyDelete.as_view(), name='confirm_delete'),
    # path('add_department/', views.DepartmentCreateView.as_view(), name='add_department'),
    # path('structure/<int:pk>/', views.StructureDetailView.as_view(), name='structure'),
    # path('structure/<int:id>/', views.show_structure, name='structure'),
    # path('structure/', views.show_structure, name='structure'),
    # path('departments/', views.DepartmentsListView.as_view(), name='departments'),


]

admin_panel/quiz_app/urls.py
from django.urls import path
from quiz_app import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'quiz_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
    path('<int:poll_id>/vote/', csrf_exempt(views.vote), name='vote'),
    path('<int:pk>)/results/', csrf_exempt(views.ResultsView.as_view()), name='results'),


]

admin_panel/surveys_app/urls.py
from django.urls import path
from surveys_app import views
from surveys_app.forms import StepOneForm, StepTwoForm, StepThreeForm

app_name = 'surveys_app'

# named_contact_forms = (
#     ('contactdata', StepOneForm),
#     ('leavemessage', StepTwoForm),
# )

urlpatterns = [
    path('', views.main_view, name='index'),

    path('add_survey/', views.FormWizardView.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='add_survey'),
    path('surveys/', views.SurveysListView.as_view(), name='surveys'),
    path('survey/<int:pk>/', views.SurveyDetailView.as_view(), name='survey'),
    path('del_survey/<int:pk>/', views.SurveyDeleteView.as_view(), name='del_survey'),

    path('hello/<int:pk>/', views.HelloUpdateView.as_view(), name='hello'),
    path('info/<int:pk>/', views.InfoUpdateView.as_view(), name='info'),
    path('bye/<int:pk>/', views.ByeUpdateView.as_view(), name='bye'),
    path('upd_page/<int:pk>/', views.PageUpdateView.as_view(), name='upd_page'),
    path('page/<int:pk>/', views.PageDetailView.as_view(), name='page'),
    path('add/<int:pk>/', views.AddPageCreateView.as_view(), name='add'),
    path('del_page/<int:pk>/', views.PageDeleteView.as_view(), name='del_page'),

    path('add_question/<int:pk>/', views.PageQuestionDetailView.as_view(), name='add_question'),
    path('add_question2/<int:pk>/', views.QuestionCreateView.as_view(), name='add_question2'),
    path('upd_question/<int:pk>/', views.QuestionUpdateView.as_view(), name='upd_question'),
    path('del_question/<int:pk>/', views.QuestionDeleteView.as_view(), name='del_question'),

    path('add_answer/<int:pk>/', views.QuestionAnswerDetailView.as_view(), name='add_answer'),
    path('add_answer2/<int:pk>/', views.QuestionAnswerCreateView.as_view(), name='add_answer2'),

    path('welcome/<int:pk>/', views.SurveyWelcome.as_view(), name='welcome'),
    # path('welcome/<slug:slug>/', views.SurveyWelcome.as_view(), name='welcome'),
    path('instruction/<int:pk>/', views.SurveyInstruction.as_view(), name='instruction'),
    path('see_you_later/<int:pk>/', views.SurveySeeYouLater.as_view(), name='see_you_later'),
    path('pages/<survey_id>', views.SurveyPagesListViewDemo.as_view(), name='pages'),
    path('create/', views.create_respond, name='create'),
    path('pages_d/<int:pk>/', views.PageResponseDetailView.as_view(), name='pages_d'),
    path('pages_d2/<int:pk>/', views.ResponseCreateView.as_view(), name='pages_d2'),
    path('pages_d4/<int:pk>/', views.ResponseCreateView2.as_view(), name='pages_d4'),
    path('pages_d3/<int:pk>/', views.StartSurveyCreateView.as_view(), name='pages_d3'),
    path('questions/<survey_id>', views.SurveyQuestionsListView.as_view(), name='questions'),



]

admin_panel/users_app/urls.py
from django.urls import path
from users_app import views
from django.contrib.auth.views import LogoutView


app_name = 'users_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('search/', views.UserSearchView.as_view(), name='search_results'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('profile/<int:pk>/', views.UserUpdateView.as_view(), name='profile'),
    path('confirm_delete/<int:pk>/', views.UserDelete.as_view(), name='confirm_delete'),
    path('passchange/<int:pk>/', views.UserPasswordChangeView.as_view(), name='passchange'),
    path('passreset/<int:pk>/', views.UserPasswordResetView.as_view(), name='passreset'),

    ]

admin_panel/templates/base.html
{% load static %}
{% load fontawesome_5 %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %} {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css' %}"
        rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
  {% fontawesome_5_static %}

  <!-- Custom styles for this template-->
  <link href="{% static 'bootstrap/css/sb-admin-2.min.css' %}"
        rel="stylesheet">
<!--  <link rel="stylesheet"-->
<!--        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"-->
<!--        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"-->
<!--        crossorigin="anonymous">-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"-->
<!--            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"-->
<!--            crossorigin="anonymous"></script>-->

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'companies:companies' %}">

        <div class="sidebar-brand-icon">
          <i class="fas fa-fw fa-bars"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin панель<sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">



      <!-- Heading -->
      <div class="sidebar-heading">
        УПРАВЛЕНИЕ
      </div>






      <!-- Nav Item - Companies Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'companies:companies' %}">

          <i class="fas fa-sitemap fa-cog "></i>
          <span>Компании</span>
        </a>
      </li>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
         <a class="nav-link collapsed" href="{% url 'surveys:surveys' %}">
          <i class="fas fa-file-alt"></i>
          <span>Опросы</span>
        </a>
      </li>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
         <a class="nav-link collapsed" href="{% url 'users:users' %}">
          <i class="fas fa-user"></i>
          <span>Пользователи</span>
        </a>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->




      <!-- Heading -->


      <!-- Nav Item - Pages Collapse Menu -->
      {% if user.is_authenticated %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Авторизация</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">


<!--                <h6 class="collapse-header">Авторизация:</h6>-->
                <a class="collapse-item" href="{% url 'users:login' %}">Вход</a>
                <a class="collapse-item" href="{% url 'users:register' %}">Регистрация</a>
                <a class="collapse-item" href="forgot-password.html">Забыли пароль?</a>

          </div>
        </div>
      </li>
       {% endif %}





      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->



          {% block content %} {% endblock %}

      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
          integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
          crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
  <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'bootstrap/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'bootstrap/vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'bootstrap/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'bootstrap/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>