admin_panel/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from companies_app.api_views import CompanyViewSet, DepartmentViewSet
from users_app.api_views import UserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'departments', DepartmentViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys_app.urls', namespace='surveys')),
    path('companies/', include('companies_app.urls', namespace='companies')),
    path('users/', include('users_app.urls', namespace='users')),
    path('quiz/', include('quiz_app.urls', namespace='quiz')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

admin_panel/companies_app/urls.py
from django.urls import path
from companies_app import views

app_name = 'companies_app'

urlpatterns = [


    path('companies/', views.CompaniesListView.as_view(), name='companies'),
    path('search/', views.CompanySearchView.as_view(), name='search_results'),
    path('users/<int:pk>/', views.CompanyDetailView.as_view(), name='users'),
    path('company_structure/<int:pk>/', views.CompanyDepartmentsDetailView.as_view(), name='company_structure'),
    path('surveys/<int:pk>/', views.CompanySurveysDetailView.as_view(), name='surveys'),
    path('company_add_department/<int:pk>/', views.AddDepartmentDetailView.as_view(), name='company_add_department'),
    path('add_department/<int:pk>/', views.AddDepartmentCreateView.as_view(), name='add_department'),
    path('create/', views.CompanyCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.CompanyUpdateView.as_view(), name='update'),
    path('confirm_delete/<int:pk>/', views.CompanyDelete.as_view(), name='confirm_delete'),
    # path('add_department/', views.DepartmentCreateView.as_view(), name='add_department'),
    # path('structure/<int:pk>/', views.StructureDetailView.as_view(), name='structure'),
    # path('structure/<int:id>/', views.show_structure, name='structure'),
    # path('structure/', views.show_structure, name='structure'),
    # path('departments/', views.DepartmentsListView.as_view(), name='departments'),


]

admin_panel/quiz_app/urls.py
from django.urls import path
from quiz_app import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'quiz_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
    path('<int:poll_id>/vote/', csrf_exempt(views.vote), name='vote'),
    path('<int:pk>)/results/', csrf_exempt(views.ResultsView.as_view()), name='results'),


]

admin_panel/surveys_app/urls.py
from django.urls import path
from surveys_app import views
from surveys_app.forms import StepOneForm, StepTwoForm, StepThreeForm

app_name = 'surveys_app'

# named_contact_forms = (
#     ('contactdata', StepOneForm),
#     ('leavemessage', StepTwoForm),
# )

urlpatterns = [
    path('', views.main_view, name='index'),

    path('add_survey/', views.FormWizardView.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='add_survey'),
    path('surveys/', views.SurveysListView.as_view(), name='surveys'),
    path('survey/<int:pk>/', views.SurveyDetailView.as_view(), name='survey'),
    path('del_survey/<int:pk>/', views.SurveyDeleteView.as_view(), name='del_survey'),

    path('hello/<int:pk>/', views.HelloUpdateView.as_view(), name='hello'),
    path('info/<int:pk>/', views.InfoUpdateView.as_view(), name='info'),
    path('bye/<int:pk>/', views.ByeUpdateView.as_view(), name='bye'),
    path('upd_page/<int:pk>/', views.PageUpdateView.as_view(), name='upd_page'),
    path('page/<int:pk>/', views.PageDetailView.as_view(), name='page'),
    path('add/<int:pk>/', views.AddPageCreateView.as_view(), name='add'),
    path('del_page/<int:pk>/', views.PageDeleteView.as_view(), name='del_page'),

    path('add_question/<int:pk>/', views.PageQuestionDetailView.as_view(), name='add_question'),
    path('add_question2/<int:pk>/', views.QuestionCreateView.as_view(), name='add_question2'),
    path('upd_question/<int:pk>/', views.QuestionUpdateView.as_view(), name='upd_question'),
    path('del_question/<int:pk>/', views.QuestionDeleteView.as_view(), name='del_question'),

    path('add_answer/<int:pk>/', views.QuestionAnswerDetailView.as_view(), name='add_answer'),
    path('add_answer2/<int:pk>/', views.QuestionAnswerCreateView.as_view(), name='add_answer2'),

    path('welcome/<int:pk>/', views.SurveyWelcome.as_view(), name='welcome'),
    # path('welcome/<slug:slug>/', views.SurveyWelcome.as_view(), name='welcome'),
    path('instruction/<int:pk>/', views.SurveyInstruction.as_view(), name='instruction'),
    path('see_you_later/<int:pk>/', views.SurveySeeYouLater.as_view(), name='see_you_later'),
    path('pages/<survey_id>', views.SurveyPagesListViewDemo.as_view(), name='pages'),
    path('create/', views.create_respond, name='create'),
    path('pages_d/<int:pk>/', views.PageResponseDetailView.as_view(), name='pages_d'),
    path('pages_d2/<int:pk>/', views.ResponseCreateView.as_view(), name='pages_d2'),
    path('pages_d4/<int:pk>/', views.ResponseCreateView2.as_view(), name='pages_d4'),
    path('pages_d3/<int:pk>/', views.StartSurveyCreateView.as_view(), name='pages_d3'),
    path('questions/<survey_id>', views.SurveyQuestionsListView.as_view(), name='questions'),



]

admin_panel/users_app/urls.py
from django.urls import path
from users_app import views
from django.contrib.auth.views import LogoutView


app_name = 'users_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('search/', views.UserSearchView.as_view(), name='search_results'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('profile/<int:pk>/', views.UserUpdateView.as_view(), name='profile'),
    path('confirm_delete/<int:pk>/', views.UserDelete.as_view(), name='confirm_delete'),
    path('passchange/<int:pk>/', views.UserPasswordChangeView.as_view(), name='passchange'),
    path('passreset/<int:pk>/', views.UserPasswordResetView.as_view(), name='passreset'),

    ]

admin_panel/companies_app/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название')
    logo = models.ImageField(null=True, blank=True, upload_to='company_logo', verbose_name='Логотип')

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'компании'

    def __str__(self):
        return self.name


class Department(MPTTModel):
    department_name = models.CharField(max_length=64, unique=True, verbose_name='Подразделение')
    head_of_department = models.CharField(max_length=64, null=True, blank=True)
    code = models.PositiveIntegerField(null=True, blank=True)
    workers = models.PositiveIntegerField(null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'

    class MPTTMeta:
        order_insertion_by = ['department_name']

    def __str__(self):
        return self.department_name

admin_panel/surveys_app/models.py
import uuid

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from companies_app.models import Company
from django.utils.timezone import now
from fontawesome_5.fields import IconField


def random_string():
    return str(uuid.uuid4().hex[:5].upper())


# Create your models here.
class Language(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        return self.name


class Survey(models.Model):
    name = models.CharField(max_length=64)
    is_draft = models.BooleanField(default=True)
    is_active = models.BooleanField(default=False)
    slug = models.SlugField(null=True, blank=True)
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.CASCADE)
    hello_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Приветствие')
    hello_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    info_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Инструкция')
    info_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    bye_title = models.CharField(max_length=32, null=True, blank=True, verbose_name='Завершение')
    bye_text = models.TextField(max_length=256, null=True, blank=True, verbose_name='ТЕКСТ')
    created_day = models.DateField(default=now)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    contacts = models.TextField(max_length=128, null=True, blank=True)
    answers_counter = models.PositiveIntegerField(null=True, blank=True)
    language = models.ManyToManyField(Language, blank=True,  default='1')

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'опросы'

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('surveys:welcome', kwargs={'slug': self.slug})


class Page(models.Model):
    number = models.SmallIntegerField(null=True, blank=True)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    page_name = models.CharField(max_length=32,  blank=True)
    page_help = models.CharField(max_length=128, blank=True)

    def page_number(self):
        pages = Page.objects.filter(survey=self.survey)
        i = 1
        for page in pages:
            page.number = i
            page.save()
            i += 1
        return self.number

    def get_questions(self):
        questions = self.question_set.all()
        return questions

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'Страницы'


class Question(MPTTModel):
    TYPE_QUESTION = (
        ("Mono", "Mono"),
        ("Poly", "Poly"),
        ("Text", "Text"),
    )
    question_type = models.CharField(max_length=255, choices=TYPE_QUESTION, default='Mono')
    question_title = models.CharField(max_length=128, null=True, blank=True)
    question_help = models.CharField(max_length=128, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='question_image')
    page = models.ForeignKey(Page, on_delete=models.CASCADE, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'вопросы'


class Answer(models.Model):
    icon = IconField(blank=True, null=True)
    question = models.ManyToManyField(Question, blank=True)
    name = models.CharField(max_length=64)
    active_answer = models.BooleanField(default=False)
    radio_buttons = models.BooleanField(default=False)
    drop_down_list = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Предлагаемый вариант ответа'
        verbose_name_plural = 'Предлагаемые варианты ответов'

    def __str__(self):
        return self.name


class UserCode(models.Model):
    code = models.CharField(max_length=5, unique=True, default=random_string)


class Response(models.Model):
    code = models.ForeignKey(UserCode, on_delete=models.CASCADE, null=True, blank=True,)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, blank=True,)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True,)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True,)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Полученный ответ'
        verbose_name_plural = 'Полученные ответы'

admin_panel/users_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group
from django.db import models
from django.utils.translation import ugettext_lazy as _
from companies_app.models import Company


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""
    username = None
    email = models.EmailField(_('email address'), unique=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_avatars')
    companies = models.ManyToManyField(Company, blank=True, verbose_name='Компании')
    groups = models.ManyToManyField(Group, blank=True, verbose_name='Группы')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        # ordering = ["last_name"]
        ordering = ["email"]

admin_panel/companies_app/forms.py
from django import forms
from .models import Department


class DepartmentForm(forms.ModelForm):
    def __init__(self, new_id, *args, **kwargs):
        super(DepartmentForm, self).__init__(*args, **kwargs)
        self.fields['parent'].queryset = Department.objects.all().filter(company=new_id)

    department_name = forms.CharField(label='Название',
                                      widget=forms.TextInput(
                                          attrs={'placeholder': 'Name', 'class': 'form-control rounded-0'}))

    class Meta:
        model = Department
        exclude = ('company',)

admin_panel/companies_app/templates/companies_app/companies.html
{% extends "base.html" %}

{% block title %} Компании {% endblock %}

{% block content %}

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form method="GET"
                  action="{% url 'companies:search_results' %}"
                  class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text"
                           class="form-control bg-light border-0 small"
                           placeholder="Поиск ..."
                           aria-label="Search"
                           aria-describedby="basic-addon2"
                           name="q">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                        {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                        {% endif %}
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Выход
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
            <!-- Page Heading -->
            <i class="fa fa-sitemap"> Управление</i>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0" style="color:black;">Компании</h1>
                <a href="{% url 'companies:create' %}"
                   class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm " style="border-radius:12px;">
                    <i class="fas fa-sm text-white-50"></i>
                    СОЗДАТЬ КОМПАНИЮ</a>
            </div>
            <!-- Content Row -->
            <div class="row col-md-12">

                {% for item in object_list %}
                <!-- Companies Cards  -->
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col-lg-2">
                                    {% if item.logo %}
                                    <img src="{{item.logo.url}}" width="40">
                                    {% else %}
                                    <i class="fas fa-sitemap fa-2x text-gray-300"> </i>
                                    {% endif %}
                                </div>
                                <div class="col-lg-9" style="padding-left: 10px;">
                                    <a href="{% url 'companies:surveys' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="font-weight-bold text-primary text-uppercase mb-1">
                                            {{ item.name }}
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <br>

                            <div class="row no-gutters ">
                                <div class="col-4">
                                    <a href="{% url 'companies:company_structure' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="row" style="color:black;">
                                            <div class="col  text-center">
                                                {{ item.department_set.all|length }}
                                            </div>
                                        </div>
                                        <div class="row" style="color:gray;">
                                            <div class="col d-flex justify-content-center text-center">Структуры</div>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-4">
                                    <a href="{% url 'companies:users' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="row" style="color:black;">
                                            <div class="col  text-center">{{ item.user_set.all|length }}</div>
                                        </div>
                                        <div class="row" style="color:gray;">
                                            <div class="col d-flex justify-content-center text-center">
                                                Сотрудники
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-4">
                                    <a href="{% url 'companies:surveys' pk=item.pk %}" style="text-decoration: none;">
                                    <div class="row" style="color:black;">
                                        <div class="col  text-center">{{ item.survey_set.all|length }}</div>
                                    </div>
                                    <div class="row" style="color:gray;">
                                        <div class="col d-flex justify-content-center text-center">
                                            Опросы
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        <!-- /.container-fluid -->
        {% endblock %}
    </div>
</div>

admin_panel/companies_app/templates/companies_app/search_results.html
{% extends "base.html" %}
{% load mptt_tags %}
{% block title %} Карточка компании {% endblock %}

{% block content %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        РЕЗУЛЬТАТЫ ПОИСКА

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>



            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                    {% if request.user.avatar %}
                        <img class="img-profile rounded-circle" src="{{request.user.avatar.url}}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Выход
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="row col-md-12">
                {% for item in object_list %}
                <!-- Companies Cards  -->
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col-lg-2">
                                    {% if item.logo %}
                                    <img src="{{item.logo.url}}" width="40">
                                    {% else %}
                                    <i class="fas fa-sitemap fa-2x text-gray-300"> </i>
                                    {% endif %}
                                </div>
                                <div class="col-lg-9" style="padding-left: 10px;">
                                    <a href="{% url 'companies:surveys' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="font-weight-bold text-primary text-uppercase mb-1">
                                            {{ item.name }}
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <br>

                            <div class="row">
                                <div class="col-4">
                                    <a href="{% url 'companies:company_structure' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="row" style="color:black;">
                                            <div class="col  text-center">
                                                {{ item.department_set.all|length }}
                                            </div>
                                        </div>
                                        <div class="row" style="color:gray;">
                                            <div class="col d-flex justify-content-center text-center">Структуры</div>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-4">
                                    <a href="{% url 'companies:users' pk=item.pk %}" style="text-decoration: none;">
                                        <div class="row" style="color:black;">
                                            <div class="col  text-center">{{ item.user_set.all|length }}</div>
                                        </div>
                                        <div class="row" style="color:gray;">
                                            <div class="col d-flex justify-content-center text-center">
                                                Сотрудники
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-4">
                                    <a href="{% url 'companies:surveys' pk=item.pk %}" style="text-decoration: none;">
                                    <div class="row" style="color:black;">
                                        <div class="col  text-center">{{ item.survey_set.all|length }}</div>
                                    </div>
                                    <div class="row" style="color:gray;">
                                        <div class="col d-flex justify-content-center text-center">
                                            Опросы
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>




</div>
<!-- /.container-fluid -->

{% endblock %}